import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from 'next-themes';
import { Inter, Montserrat } from 'next/font/google';
import "@/src/styles/globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',  // expose as CSS variable
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ken's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${montserrat.variable}  h-full antialiased`}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      
      <body className="min-h-full flex flex-col transition-all duration-300 ease-in-out">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          {children}
        </ThemeProvider>
        </body>
      
    </html>
  );
}
